"""add model_cooldowns

Revision ID: 6aa5b8df0d23
Revises: fb4736f26bf9
Create Date: 2026-04-23 17:54:31.387253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa5b8df0d23'
down_revision: Union[str, Sequence[str], None] = 'fb4736f26bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('model_cooldowns', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'model_cooldowns')
    # ### end Alembic commands ###
