"""remove: cooldown_until, consecutive_failures, and total_calls

Revision ID: 740c09128175
Revises: 6aa5b8df0d23
Create Date: 2026-04-24 11:33:49.256891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '740c09128175'
down_revision: Union[str, Sequence[str], None] = '6aa5b8df0d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'total_calls')
    op.drop_column('api_keys', 'cooldown_until')
    op.drop_column('api_keys', 'consecutive_failures')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('consecutive_failures', sa.INTEGER(), nullable=False))
    op.add_column('api_keys', sa.Column('cooldown_until', sa.DATETIME(), nullable=True))
    op.add_column('api_keys', sa.Column('total_calls', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
