"""feat: add schedule model

Revision ID: b729aec83ffb
Revises: c4e9a7b2d1f0
Create Date: 2026-05-13 11:35:22.789305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b729aec83ffb'
down_revision: Union[str, Sequence[str], None] = 'c4e9a7b2d1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_events_session_id'), table_name='schedule_events')
    op.drop_column('schedule_events', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_events', sa.Column('session_id', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_schedule_events_session_id'), 'schedule_events', ['session_id'], unique=False)
    # ### end Alembic commands ###
